### ISSUE TITLE
Zodiac Sign Information

### ISSUE THREAD

**Issue by codewarnab** [codewarnab/age-calculator-app#3]
**Implement a feature in the Age Calculator to showcase the user's Zodiac Sign based on their birth date. This addition will provide users with insightful information about their astrological sign, enriching their experience with additional knowledge and personalized details.**

**Comment by codewarnab** [comment]
this is isseue is completed in [pr5](https://github.com/codewarnab/age-calculator-app/pull/5) thanks to @motlatsimoea

**Comment by motlatsimoea** [comment]
Thank you for the for the opportunity to contribute and the positive feedback @codewarnab. I am grateful.
